[deps]
python = ">=3.7,<4"

[pip.deps]
# gymnasium dependencies installed by all...
gymnasium = ">=0.26"
ale-py = "~=0.8.0"
shimmy = ">=0.1.0,<1.0"
box2d-py = "==2.3.5"
pygame = "==2.1.3.dev8"
swig = "==4.*"
# classic-control
# pygame = "==2.1.3.dev8"
# mujoco-py
mujoco-py = ">=2.1,<2.2"
# mujoco
mujoco = ">=2.3.1.post1"
imageio = ">=2.14.1"
# toy-text
# pygame = "==2.1.3.dev8"
# jax
jax = "==0.3.24"
jaxlib = "==0.3.24"
# other
lz4 = ">=3.1.0"
opencv-python = ">=3.0"
matplotlib = ">=3.0"
moviepy = ">=1.0.0"
# torch = ">=1.0.0"
