[deps]
python = "=3.11"

[pip.deps]
matplotlib = ">=3.0"
imageio = ">=2.14.1"
opencv-python = ">=3.0"
box2d-py = ""
swig = ""
mujoco-py = ">=2.1,<2.2"
jaxlib = ""
pygame = ""
shimmy = ">=0.1.0,<1.0"
jax = ""
minigrid = ""
ale-py = ""
moviepy = ">=1.0.0"
mujoco = ">=2.3.1.post1"
lz4 = ">=3.1.0"

    [pip.deps.gymnasium]
    extras = ["atari", "box2d", "mujoco"]
    version = ">=1.1.1"